receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlphttp/metrics:
    endpoint: http://prometheus:9090/api/v1/otlp # Sending metrics to prometheus
    tls:
      insecure: true
  otlphttp:
    endpoint: http://tempo:4418 # sending data to tempo
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push # sending data to loki
    tls:
      insecure: true
  logging/metrics:
    verbosity: detailed
  logging/traces:
    verbosity: detailed
  logging/logs:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
      #exporters: [otlphttp/traces,logging/traces]
    metrics:
      receivers: [otlp, prometheus/collector]
      processors: [batch]
      exporters: [otlphttp/metrics]
      #exporters: [otlphttp/metrics,logging/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
      #exporters: [otlphttp/logs,logging/logs]
