{
 "title": "Auth Service",
 "tags": [ "backend-service" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Login Request (Last 5 Minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_per_rpc_count{rpc_service=\"auth.AuthService\", rpc_method=\"Login\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Auth Request (Last 5 Minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_per_rpc_count{rpc_service=\"auth.AuthService\", rpc_method=\"Me\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Register Request (Last 5 Minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_per_rpc_count{rpc_service=\"auth.AuthService\", rpc_method=\"Register\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Login Request Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_per_rpc_count{rpc_service=\"auth.AuthService\", rpc_method=\"Login\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Request Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_per_rpc_count{rpc_service=\"auth.AuthService\", rpc_method=\"Me\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Register Request Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_per_rpc_count{rpc_service=\"auth.AuthService\", rpc_method=\"Register\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Log Auth Services",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{job=\"auth\"} | json",
     "maxLines": 1000
    }
   ]
  }
 ]
}