{
 "title": "Frontend",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Login Failed (In last Hour)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(failed_login_total{job=\"frontend\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Login Success (In last Hour)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(success_login_total{job=\"frontend\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Authenticating User (last minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(failed_me_total{job=\"frontend\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Success Authenticating User (last hour)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(success_me_total{job=\"frontend\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Success Registering User (last hour)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(success_register_total{job=\"frontend\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Registering User (last hour)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(failed_register_total{job=\"frontend\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Volumes (Last 5 Minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"frontend\"} | exporter = `OTLP` [5m]))"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Success Login Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(success_login_total{job=\"frontend\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Login Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "increase(failed_login_total{job=\"frontend\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Auth Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(success_me_total{job=\"frontend\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Auth Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "increase(failed_me_total{job=\"frontend\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}