{
 "title": "User Service",
 "tags": [ "backend-service" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Get User Request (Last 5 Minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_per_rpc_count{rpc_service=\"user.UserService\", rpc_method=\"GetUser\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Create User Request (Last 5 Minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_per_rpc_count{rpc_service=\"user.UserService\", rpc_method=\"CreateUser\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get User Request Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_per_rpc_count{rpc_service=\"user.UserService\", rpc_method=\"GetUser\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create User Request Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(rpc_server_requests_per_rpc_count{rpc_service=\"user.UserService\", rpc_method=\"CreateUser\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"user\"} | json"
    }
   ]
  }
 ]
}